var langLayoutObj = {
    'BG-BG': {
        'Apply theme': 'Прилагане на тема: ',
        'Cancel': 'Отказ',
        'Choose your favorite theme.': 'Изберете любимата си тема.',
        'Current time zone': 'Текуща часова зона',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Помощ',
        'Language': 'Език',
        'Language and time zone': 'Език и часова зона',
        'My account': 'Моят акаунт',
        'My accounts': 'Моите акаунти',
        'My profile': 'За мен',
        'Notifications': 'Известия',
        'Save': 'Запиши',
        'Selected theme': 'Избрана тема: ',
        'Settings': 'Настройки',
        'Sign out': 'Излизане',
        'Theme': 'Тема',
        'Your apps': 'Вашите приложения'
    },
    'CS-CZ': {
        'Apply theme': 'Použít motiv: ',
        'Cancel': 'Zrušit',
        'Choose your favorite theme.': 'Zvolte svůj oblíbený motiv.',
        'Current time zone': 'Aktuální časové pásmo',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Nápověda',
        'Language': 'Jazyk',
        'Language and time zone': 'Jazyk a časové pásmo',
        'My account': 'Můj účet',
        'My accounts': 'Moje účty',
        'My profile': 'O mně',
        'Notifications': 'Oznámení',
        'Save': 'Uložit',
        'Selected theme': 'Vybraný motiv: ',
        'Settings': 'Nastavení',
        'Sign out': 'Odhlásit se',
        'Theme': 'Motiv',
        'Your apps': 'Vaše aplikace'
    },
    'DE-AT': {
        'Apply theme': 'Design anwenden: ',
        'Cancel': 'Abbrechen',
        'Choose your favorite theme.': 'Wählen Sie Ihr Lieblingsdesign aus.',
        'Current time zone': 'Aktuelle Zeitzone',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Hilfe',
        'Language': 'Sprache',
        'Language and time zone': 'Sprache und Zeitzone',
        'My account': 'Mein Konto',
        'My accounts': 'Meine Konten',
        'My profile': 'Über mich',
        'Notifications': 'Benachrichtigungen',
        'Save': 'Speichern',
        'Selected theme': 'Ausgewähltes Design: ',
        'Settings': 'Einstellungen',
        'Sign out': 'Abmelden',
        'Theme': 'Design',
        'Your apps': 'Ihre Apps'
    },
    'ET-EE': {
        'Apply theme': 'Rakenda kujundus: ',
        'Cancel': 'Loobu',
        'Choose your favorite theme.': 'Saate valida oma lemmikkujunduse.',
        'Current time zone': 'Praegune ajavöönd',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Spikker',
        'Language': 'Keel',
        'Language and time zone': 'Keel ja ajavöönd',
        'My account': 'Minu konto',
        'My accounts': 'Minu kontod',
        'My profile': 'Minust',
        'Notifications': 'Teatised',
        'Save': 'Salvesta',
        'Selected theme': 'Valitud kujundus: ',
        'Settings': 'Sätted',
        'Sign out': 'Logi välja',
        'Theme': 'Kujundus',
        'Your apps': 'Teie rakendused'
    },
    'EN-GB': {
        'Apply theme': 'Apply theme: ',
        'Cancel': 'Cancel',
        'Choose your favorite theme.': 'Choose your favorite theme.',
        'Current time zone': 'Current time zone',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Help',
        'Language': 'Language',
        'Language and time zone': 'Language and time zone',
        'My account': 'My account',
        'My accounts': 'My accounts',
        'My profile': 'My profile',
        'Notifications': 'Notifications',
        'Save': 'Save',
        'Selected theme': 'Selected theme: ',
        'Settings': 'Settings',
        'Sign out': 'Sign out',
        'Theme': 'Theme',
        'Your apps': 'Your apps'
    },
    'HR-HR': {
        'Apply theme': 'Primijeni temu: ',
        'Cancel': 'Odustani',
        'Choose your favorite theme.': 'Odaberite omiljenu temu.',
        'Current time zone': 'Trenutna vremenska zona',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoć',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik i vremenska zona',
        'My account': 'Moj račun',
        'My accounts': 'Moji računi',
        'My profile': 'O meni',
        'Notifications': 'Obavijesti',
        'Save': 'Spremi',
        'Selected theme': 'Odabrana tema: ',
        'Settings': 'Postavke',
        'Sign out': 'Odjava',
        'Theme': 'Tema',
        'Your apps': 'Vaše aplikacije'
    },
    'HU-HU': {
        'Apply theme': 'Téma alkalmazása: ',
        'Cancel': 'Mégse',
        'Choose your favorite theme.': 'A kedvenc téma kiválasztása.',
        'Current time zone': 'Jelenlegi időzóna',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Súgó',
        'Language': 'Nyelv',
        'Language and time zone': 'Nyelv és időzóna',
        'My account': 'Saját fiók',
        'My accounts': 'Saját fiókok',
        'My profile': 'Rólam',
        'Notifications': 'Értesítések',
        'Save': 'Mentés',
        'Selected theme': 'Választott téma: ',
        'Settings': 'Beállítások',
        'Sign out': 'Kijelentkezés',
        'Theme': 'Téma',
        'Your apps': 'Saját appok'
    },
    'KK-KZ': {
        'Apply theme': 'Тақырыпты қолдану: ',
        'Cancel': 'Бас тарту',
        'Choose your favorite theme.': 'Сүйікті тақырыбыңызды таңдаңыз.',
        'Current time zone': 'Ағымдағы уақыт белдеуі',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Анықтама',
        'Language': 'Тіл',
        'Language and time zone': 'Тіл және уақыт белдеуі',
        'My account': 'Менің тіркелгім',
        'My accounts': 'Менің тіркелгілерім',
        'My profile': 'Мен туралы мәлімет',
        'Notifications': 'Хабарландырулар',
        'Save': 'Сақтау',
        'Selected theme': 'Таңдалған тақырып: ',
        'Settings': 'Параметрлер',
        'Sign out': 'Шығу',
        'Theme': 'Тақырып',
        'Your apps': 'Бағдарламаларыңыз'
    },
    'LT-LT': {
        'Apply theme': 'Taikyti temą: ',
        'Cancel': 'Atšaukti',
        'Choose your favorite theme.': 'Pasirinkite mėgstamą temą.',
        'Current time zone': 'Dabartinė laiko juosta',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Žinynas',
        'Language': 'Kalba',
        'Language and time zone': 'Kalba ir laiko juosta',
        'My account': 'Mano paskyra',
        'My accounts': 'Mano paskyros',
        'My profile': 'Apie mane',
        'Notifications': 'Pranešimai',
        'Save': 'Įrašyti',
        'Selected theme': 'Pasirinkta tema: ',
        'Settings': 'Parametrai',
        'Sign out': 'Atsijungti',
        'Theme': 'Tema',
        'Your apps': 'Jūsų programos'
    },
    'PL-PL': {
        'Apply theme': 'Zastosuj motyw: ',
        'Cancel': 'Anuluj',
        'Choose your favorite theme.': 'Wybierz ulubiony motyw.',
        'Current time zone': 'Bieżąca strefa czasowa',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoc',
        'Language': 'Język',
        'Language and time zone': 'Język i strefa czasowa',
        'My account': 'Moje konto',
        'My accounts': 'Moje konta',
        'My profile': 'O mnie',
        'Notifications': 'Powiadomienia',
        'Save': 'Zapisz',
        'Selected theme': 'Wybrany motyw: ',
        'Settings': 'Ustawienia',
        'Sign out': 'Wyloguj',
        'Theme': 'Motyw',
        'Your apps': 'Twoje aplikacje'
    },
    'RO-RO': {
        'Apply theme': 'Aplicați tema: ',
        'Cancel': 'Anulare',
        'Choose your favorite theme.': 'Alegeți tema preferată.',
        'Current time zone': 'Fus orar actual',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Ajutor',
        'Language': 'Limbă',
        'Language and time zone': 'Limbă și fus orar',
        'My account': 'Contul meu',
        'My accounts': 'Conturile mele',
        'My profile': 'Despre mine',
        'Notifications': 'Notificări',
        'Save': 'Salvare',
        'Selected theme': 'Tema selectată: ',
        'Settings': 'Setări',
        'Sign out': 'Deconectare',
        'Theme': 'Temă',
        'Your apps': 'Aplicațiile dvs.'
    },
    'SR-LATN-CS': {
        'Apply theme': 'Primena teme: ',
        'Cancel': 'Otkaži',
        'Choose your favorite theme.': 'Odaberite svoju omiljenu temu.',
        'Current time zone': 'Trenutna vremenska zona',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoć',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik i vremenska zona',
        'My account': 'Moj nalog',
        'My accounts': 'Moji nalozi',
        'My profile': 'O meni',
        'Notifications': 'Obaveštenja',
        'Save': 'Sačuvaj',
        'Selected theme': 'Izabrana tema: ',
        'Settings': 'Postavke',
        'Sign out': 'Odjavi se',
        'Theme': 'Tema',
        'Your apps': 'Vaše aplikacije'
    },
    'RU-RU': {
        'Apply theme': 'Применить тему: ',
        'Cancel': 'Отмена',
        'Choose your favorite theme.': 'Выберите понравившуюся тему.',
        'Current time zone': 'Текущий часовой пояс',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Справка',
        'Language': 'Язык',
        'Language and time zone': 'Язык и часовой пояс',
        'My account': 'Моя учетная запись',
        'My accounts': 'Мои учетные записи',
        'My profile': 'Мои данные',
        'Notifications': 'Уведомления',
        'Save': 'Сохранить',
        'Selected theme': 'Выбранная тема: ',
        'Settings': 'Параметры',
        'Sign out': 'Выйти',
        'Theme': 'Тема',
        'Your apps': 'Ваши приложения'
    },
    'SL-SI': {
        'Apply theme': 'Uporabite temo: ',
        'Cancel': 'Prekliči',
        'Choose your favorite theme.': 'Izberite priljubljeno temo.',
        'Current time zone': 'Trenutni časovni pas',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoč',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik in časovni pas',
        'My account': 'Moj račun',
        'My accounts': 'Moji računi',
        'My profile': 'O meni',
        'Notifications': 'Obvestila',
        'Save': 'Shrani',
        'Selected theme': 'Izbrana tema: ',
        'Settings': 'Nastavitve',
        'Sign out': 'Izpis',
        'Theme': 'Tema',
        'Your apps': 'Vaše aplikacije'
    },
    'SK-SK': {
        'Apply theme': 'Použiť motív: ',
        'Cancel': 'Zrušiť',
        'Choose your favorite theme.': 'Vyberte si obľúbený motív.',
        'Current time zone': 'Aktuálne časové pásmo',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomocník',
        'Language': 'Jazyk',
        'Language and time zone': 'Jazyk a časové pásmo',
        'My account': 'Moje konto',
        'My accounts': 'Moje kontá',
        'My profile': 'O mne',
        'Notifications': 'Oznámenia',
        'Save': 'Uložiť',
        'Selected theme': 'Vybratý motív: ',
        'Settings': 'Nastavenie',
        'Sign out': 'Odhlásiť sa',
        'Theme': 'Motív',
        'Your apps': 'Vaše aplikácie'
    },
    'TR-TR': {
        'Apply theme': 'Temayı uygula: ',
        'Cancel': 'İptal',
        'Choose your favorite theme.': 'Beğendiğiniz temayı seçin.',
        'Current time zone': 'Geçerli saat dilimi',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Yardım',
        'Language': 'Dil',
        'Language and time zone': 'Dil ve saat dilimi',
        'My account': 'Hesabım',
        'My accounts': 'Hesaplarım',
        'My profile': 'Hakkımda',
        'Notifications': 'Bildirimler',
        'Save': 'Kaydet',
        'Selected theme': 'Seçili tema: ',
        'Settings': 'Ayarlar',
        'Sign out': 'Oturumu kapat',
        'Theme': 'Tema',
        'Your apps': 'Uygulamalarınız'
    },
    'UK-UA': {
        'Apply theme': 'Застосувати тему: ',
        'Cancel': 'Скасувати',
        'Choose your favorite theme.': 'Виберіть улюблену тему.',
        'Current time zone': 'Поточний часовий пояс',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Довідка',
        'Language': 'Мова',
        'Language and time zone': 'Мова та часовий пояс',
        'My account': 'Мій обліковий запис',
        'My accounts': 'Мої облікові записи',
        'My profile': 'Про мене',
        'Notifications': 'Сповіщення',
        'Save': 'Зберегти',
        'Selected theme': 'Вибрана тема: ',
        'Settings': 'Параметри',
        'Sign out': 'Вийти',
        'Theme': 'Тема',
        'Your apps': 'Ваші програми'
    }
}