var langLayoutObj = {
    'BG-BG': {
        'Cancel': 'Отказ',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Помощ',
        'Language': 'Език',
        'Language and time zone': 'Език и часова зона',
        'My account': 'Моят акаунт',
        'My Accounts': 'Моите акаунти',
        'My profile': 'За мен',
        'Notifications': 'Известия',
        'Save': 'Запиши',
        'Settings': 'Настройки',
        'Sign out': 'Излизане',
        'Your apps': 'Вашите приложения'
    },
    'CS-CZ': {
        'Cancel': 'Zrušit',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Nápověda',
        'Language': 'Jazyk',
        'Language and time zone': 'Jazyk a časové pásmo',
        'My account': 'Můj účet',
        'My Accounts': 'Moje účty',
        'My profile': 'O mně',
        'Notifications': 'Oznámení',
        'Save': 'Uložit',
        'Settings': 'Nastavení',
        'Sign out': 'Odhlásit se',
        'Your apps': 'Vaše aplikace'
    },
    'DE-AT': {
        'Cancel': 'Abbrechen',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Hilfe',
        'Language': 'Sprache',
        'Language and time zone': 'Sprache und Zeitzone',
        'My account': 'Mein Konto',
        'My Accounts': 'Meine Konten',
        'My profile': 'Über mich',
        'Notifications': 'Benachrichtigungen',
        'Save': 'Speichern',
        'Settings': 'Einstellungen',
        'Sign out': 'Abmelden',
        'Your apps': 'Ihre Apps'
    },
    'ET-EE': {
        'Cancel': 'Loobu',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Spikker',
        'Language': 'Keel',
        'Language and time zone': 'Keel ja ajavöönd',
        'My account': 'Minu konto',
        'My Accounts': 'Minu kontod',
        'My profile': 'Minust',
        'Notifications': 'Teatised',
        'Save': 'Salvesta',
        'Settings': 'Sätted',
        'Sign out': 'Logi välja',
        'Your apps': 'Teie rakendused'
    },
    'EN-GB': {
        'Cancel': 'Cancel',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Help',
        'Language': 'Language',
        'Language and time zone': 'Language and time zone',
        'My account': 'My account',
        'My Accounts': 'My Accounts',
        'My profile': 'My profile',
        'Notifications': 'Notifications',
        'Save': 'Save',
        'Settings': 'Settings',
        'Sign out': 'Sign out',
        'Your apps': 'Your apps'
    },
    'HR-HR': {
        'Cancel': 'Odustani',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoć',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik i vremenska zona',
        'My account': 'Moj račun',
        'My Accounts': 'Moji računi',
        'My profile': 'O meni',
        'Notifications': 'Obavijesti',
        'Save': 'Spremi',
        'Settings': 'Postavke',
        'Sign out': 'Odjava',
        'Your apps': 'Vaše aplikacije'
    },
    'HU-HU': {
        'Cancel': 'Mégse',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Súgó',
        'Language': 'Nyelv',
        'Language and time zone': 'Nyelv és időzóna',
        'My account': 'Saját fiók',
        'My Accounts': 'Saját fiókok',
        'My profile': 'Rólam',
        'Notifications': 'Értesítések',
        'Save': 'Mentés',
        'Settings': 'Beállítások',
        'Sign out': 'Kijelentkezés',
        'Your apps': 'Saját appok'
    },
    'KK-KZ': {
        'Cancel': 'Бас тарту',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Анықтама',
        'Language': 'Тіл',
        'Language and time zone': 'Тіл және уақыт белдеуі',
        'My account': 'Менің тіркелгім',
        'My Accounts': 'Менің тіркелгілерім',
        'My profile': 'Мен туралы мәлімет',
        'Notifications': 'Хабарландырулар',
        'Save': 'Сақтау',
        'Settings': 'Параметрлер',
        'Sign out': 'Шығу',
        'Your apps': 'Бағдарламаларыңыз'
    },
    'LT-LT': {
        'Cancel': 'Atšaukti',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Žinynas',
        'Language': 'Kalba',
        'Language and time zone': 'Kalba ir laiko juosta',
        'My account': 'Mano paskyra',
        'My Accounts': 'Mano paskyros',
        'My profile': 'Apie mane',
        'Notifications': 'Pranešimai',
        'Save': 'Įrašyti',
        'Settings': 'Parametrai',
        'Sign out': 'Atsijungti',
        'Your apps': 'Jūsų programos'
    },
    'PL-PL': {
        'Cancel': 'Anuluj',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoc',
        'Language': 'Język',
        'Language and time zone': 'Język i strefa czasowa',
        'My account': 'Moje konto',
        'My Accounts': 'Moje konta',
        'My profile': 'O mnie',
        'Notifications': 'Powiadomienia',
        'Save': 'Zapisz',
        'Settings': 'Ustawienia',
        'Sign out': 'Wyloguj',
        'Your apps': 'Twoje aplikacje'
    },
    'RO-RO': {
        'Cancel': 'Anulare',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Ajutor',
        'Language': 'Limbă',
        'Language and time zone': 'Limbă și fus orar',
        'My account': 'Contul meu',
        'My Accounts': 'Conturile mele',
        'My profile': 'Despre mine',
        'Notifications': 'Notificări',
        'Save': 'Salvare',
        'Settings': 'Setări',
        'Sign out': 'Deconectare',
        'Your apps': 'Aplicațiile dvs.'
    },
    'SR-LATN-CS': {
        'Cancel': 'Otkaži',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoć',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik i vremenska zona',
        'My account': 'Moj nalog',
        'My Accounts': 'Moji nalozi',
        'My profile': 'O meni',
        'Notifications': 'Obaveštenja',
        'Save': 'Sačuvaj',
        'Settings': 'Postavke',
        'Sign out': 'Odjavi se',
        'Your apps': 'Vaše aplikacije'
    },
    'RU-RU': {
        'Cancel': 'Отмена',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Справка',
        'Language': 'Язык',
        'Language and time zone': 'Язык и часовой пояс',
        'My account': 'Моя учетная запись',
        'My Accounts': 'Мои учетные записи',
        'My profile': 'Мои данные',
        'Notifications': 'Уведомления',
        'Save': 'Сохранить',
        'Settings': 'Параметры',
        'Sign out': 'Выйти',
        'Your apps': 'Ваши приложения'
    },
    'SL-SI': {
        'Cancel': 'Prekliči',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomoč',
        'Language': 'Jezik',
        'Language and time zone': 'Jezik in časovni pas',
        'My account': 'Moj račun',
        'My Accounts': 'Moji računi',
        'My profile': 'O meni',
        'Notifications': 'Obvestila',
        'Save': 'Shrani',
        'Settings': 'Nastavitve',
        'Sign out': 'Izpis',
        'Your apps': 'Vaše aplikacije'
    },
    'SK-SK': {
        'Cancel': 'Zrušiť',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Pomocník',
        'Language': 'Jazyk',
        'Language and time zone': 'Jazyk a časové pásmo',
        'My account': 'Moje konto',
        'My Accounts': 'Moje kontá',
        'My profile': 'O mne',
        'Notifications': 'Oznámenia',
        'Save': 'Uložiť',
        'Settings': 'Nastavenie',
        'Sign out': 'Odhlásiť sa',
        'Your apps': 'Vaše aplikácie'
    },
    'TR-TR': {
        'Cancel': 'İptal',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Yardım',
        'Language': 'Dil',
        'Language and time zone': 'Dil ve saat dilimi',
        'My account': 'Hesabım',
        'My Accounts': 'Hesaplarım',
        'My profile': 'Hakkımda',
        'Notifications': 'Bildirimler',
        'Save': 'Kaydet',
        'Settings': 'Ayarlar',
        'Sign out': 'Oturumu kapat',
        'Your apps': 'Uygulamalarınız'
    },
    'UK-UA': {
        'Cancel': 'Скасувати',
        'Environment': 'Environment',
        'Environments': 'Environments',
        'Help': 'Довідка',
        'Language': 'Мова',
        'Language and time zone': 'Мова та часовий пояс',
        'My account': 'Мій обліковий запис',
        'My Accounts': 'Мої облікові записи',
        'My profile': 'Про мене',
        'Notifications': 'Сповіщення',
        'Save': 'Зберегти',
        'Settings': 'Параметри',
        'Sign out': 'Вийти',
        'Your apps': 'Ваші програми'
    }
}